encoding: utf-8
#permalink: /:year/:month/:day/:title.html
permalink: /blog/:year/:month/:day/:title
paginate: 10
#markdown: redcarpet
highlighter: pygments
#markdown: kramdown
markdown: KramdownPygments
#permalink: pretty

kramdown:
  default_lang: python

# 作者信息
author: 
  name: Loong
  email: loongfee@gmail.com
  link: http://loongfee.github.io
  github: https://github.com/loongfee
  researchgate: https://www.researchgate.net/profile/Tengfei_Long

# 站点信息
title: 淡朴若水
description: 土肥龙的博客
aphorism: 上善若水，水善利万物而不争
url: http://loongfee.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/satellite.png
favicon: /public/img/earth.png

# google analytics 设置
ga:
  id: UA-42985048-1 
  url: http://loongfee.github.io

# disqus 设置
disqus:
  shortname: loongfee

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
#cates: 
#  - Optimization
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  favorite: 收藏
  about: 关于
  newest: 最新文章
  archive: 归档