"""
it-m3u8.py
iTunes Playlist to m3u Converter
(c) 2019 9volt

Converts txt files generated by iTunes' Export Playlist feature
to the more versitile m3u8 format.
"""

import sys
import io
import os
import glob


def process(fname):
    savename = fname[:len(fname) - 3] + 'm3u8'
    songs = []

    file = io.open(fname, "r", encoding='UTF-16 LE')
    for line in file:
        index = line.rfind(':')
        if index is not -1:
            songs.append(line[index - 2:].strip())

    with open(savename, 'a', encoding='UTF-8') as file:
        for song in songs:
            file.write(f'{song}\n')
    print('Wrote {}'.format(savename))


if len(sys.argv) < 2:
    for fname in glob.glob("*.txt"):
        process(fname)
else:
    for fname in sys.argv[1:]:
        process(fname)
